FROM gradle:5.6.2-jdk8
LABEL maintainer="Oleg Yapparov <oleg.yapparov@infor.com>"
WORKDIR '/e2e'
COPY ./src ./src
COPY ./build.gradle .
COPY ./src/test/resources/Upload/1.jpg .
COPY ./src/test/resources/Upload/2.jpg .
# COPY ./src/test/resources/configuration.staging.sample ./configuration
# COPY ./src/test/resources/credentials.sample ./credentials
ENTRYPOINT gradle --rerun-tasks chrome -Premote=http://selenium-hub:4444/wd/hub